$(document).ready(function (e) {
    $(".province a").click(function () {
        $(".select_city ul").fadeOut("fast");
        $(".select_province ul").fadeToggle("fast");
        $(".city").removeClass("active_border");
        $(".province").toggleClass("active_border");
    });
    $(".city a").click(function () {
        $(".select_province ul").fadeOut("fast");
        $(".select_city ul").fadeToggle("fast");
        $(".province").removeClass("active_border");
        $(".city").toggleClass("active_border");
        $(".city a").toggleClass("arrow_active");
    });
    $(".select_province ul li").click(function () {
        var Num = $(this).index();
        var P_text = $(this).text();
        $(".select_city ul").html(city[Num]);
        $(".province span").text(P_text);
        $(".select_province ul").fadeOut();
        $(".province").removeClass("active_border");
        $(".city span").text("请选择")
    });
    $(".city_list").on("click", "li", function () {
        var P_text = $(this).text();
        $(".city span").text(P_text);
        $(".select_city ul").fadeOut();
        $(".city").removeClass("active_border");
    });
    var city = new Array(
        "<li><a href='javascript:;'>东城区</a></li><li><a href='javascript:;'>西城区</a></li><li><a href='javascript:;'>崇文区</a></li><li><a href='javascript:;'>宣武区</a></li><li><a href='javascript:;'>朝阳区</a></li><li><a href='javascript:;'>丰台区</a></li><li><a href='javascript:;'>石景山区</a></li><li><a href='javascript:;'>海淀区</a></li><li><a href='javascript:;'>门头沟区</a></li><li><a href='javascript:;'>房山区</a></li><li><a href='javascript:;'>通州区</a></li><li><a href='javascript:;'>顺义区</a></li><li><a href='javascript:;'>昌平区</a></li><li><a href='javascript:;'>大兴区</a></li><li><a href='javascript:;'>怀柔区</a></li><li><a href='javascript:;'>平谷区</a></li><li><a href='javascript:;'>密云县</a></li><li><a href='javascript:;'>延庆县</a></li><li><a href='javascript:;'>延庆镇</a></li>",
        "<li><a href='javascript:;'>和平区</a></li><li><a href='javascript:;'>河东区</a></li><li><a href='javascript:;'>河西区</a></li><li><a href='javascript:;'>南开区</a></li><li><a href='javascript:;'>河北区</a></li><li><a href='javascript:;'>红桥区</a></li><li><a href='javascript:;'>塘沽区</a></li><li><a href='javascript:;'>汉沽区</a></li><li><a href='javascript:;'>大港区</a></li><li><a href='javascript:;'>东丽区</a></li><li><a href='javascript:;'>西青区</a></li><li><a href='javascript:;'>津南区</a></li><li><a href='javascript:;'>北辰区</a></li><li><a href='javascript:;'>武清区</a></li><li><a href='javascript:;'>宝坻区</a></li><li><a href='javascript:;'>蓟县</a></li><li><a href='javascript:;'>宁河县</a></li><li><a href='javascript:;'>芦台镇</a></li><li><a href='javascript:;'>静海县</a></li><li><a href='javascript:;'>静海镇</a></li>",
        "<li><a href='javascript:;'>黄浦区</a></li><li><a href='javascript:;'>卢湾区</a></li><li><a href='javascript:;'>徐汇区</a></li><li><a href='javascript:;'>长宁区</a></li><li><a href='javascript:;'>静安区</a></li><li><a href='javascript:;'>普陀区</a></li><li><a href='javascript:;'>闸北区</a></li><li><a href='javascript:;'>虹口区</a></li><li><a href='javascript:;'>杨浦区</a></li><li><a href='javascript:;'>闵行区</a></li><li><a href='javascript:;'>宝山区</a></li><li><a href='javascript:;'>嘉定区</a></li><li><a href='javascript:;'>浦东新区</a></li><li><a href='javascript:;'>金山区</a></li><li><a href='javascript:;'>松江区</a></li><li><a href='javascript:;'>青浦区</a></li><li><a href='javascript:;'>南汇区</a></li><li><a href='javascript:;'>奉贤区</a></li><li><a href='javascript:;'>崇明县</a></li><li><a href='javascript:;'>城桥镇</a></li>",
        "<li><a href='javascript:;'>渝中区</a></li><li><a href='javascript:;'>大渡口区</a></li><li><a href='javascript:;'>江北区</a></li><li><a href='javascript:;'>沙坪坝区</a></li><li><a href='javascript:;'>九龙坡区</a></li><li><a href='javascript:;'>南岸区</a></li><li><a href='javascript:;'>北碚区</a></li><li><a href='javascript:;'>万盛区</a></li><li><a href='javascript:;'>双桥区</a></li><li><a href='javascript:;'>渝北区</a></li><li><a href='javascript:;'>巴南区</a></li><li><a href='javascript:;'>万州区</a></li><li><a href='javascript:;'>涪陵区</a></li><li><a href='javascript:;'>黔江区</a></li><li><a href='javascript:;'>长寿区</a></li><li><a href='javascript:;'>合川市</a></li><li><a href='javascript:;'>永川区市</a></li><li><a href='javascript:;'>江津市</a></li><li><a href='javascript:;'>南川市</a></li><li><a href='javascript:;'>綦江县</a></li><li><a href='javascript:;'>潼南县</a></li><li><a href='javascript:;'>铜梁县</a></li><li><a href='javascript:;'>大足县</a></li><li><a href='javascript:;'>荣昌县</a></li><li><a href='javascript:;'>璧山县</a></li><li><a href='javascript:;'>垫江县</a></li><li><a href='javascript:;'>武隆县</a></li><li><a href='javascript:;'>丰都县</a></li><li><a href='javascript:;'>城口县</a></li><li><a href='javascript:;'>梁平县</a></li><li><a href='javascript:;'>开县</a></li><li><a href='javascript:;'>巫溪县</a></li><li><a href='javascript:;'>巫山县</a></li><li><a href='javascript:;'>奉节县</a></li><li><a href='javascript:;'>云阳县</a></li><li><a href='javascript:;'>忠县</a></li><li><a href='javascript:;'>石柱土家族自治县</a></li><li><a href='javascript:;'>彭水苗族土家族自治县</a></li><li><a href='javascript:;'>酉阳土家族苗族自治县</a></li><li><a href='javascript:;'>秀山土家族苗族自治县</a></li>",
        "<li><a href='javascript:;'>石家庄市</a></li><li><a href='javascript:;'>张家口市</a></li><li><a href='javascript:;'>承德市</a></li><li><a href='javascript:;'>秦皇岛市</a></li><li><a href='javascript:;'>唐山市</a></li><li><a href='javascript:;'>廊坊市</a></li><li><a href='javascript:;'>保定市</a></li><li><a href='javascript:;'>衡水市</a></li><li><a href='javascript:;'>沧州市</a></li><li><a href='javascript:;'>邢台市</a></li><li><a href='javascript:;'>邯郸市</a></li>",
        "<li><a href='javascript:;'>太原市</a></li><li><a href='javascript:;'>朔州市</a></li><li><a href='javascript:;'>大同市</a></li><li><a href='javascript:;'>阳泉市</a></li><li><a href='javascript:;'>长治市</a></li><li><a href='javascript:;'>晋城市</a></li><li><a href='javascript:;'>忻州市</a></li><li><a href='javascript:;'>晋中市</a></li><li><a href='javascript:;'>临汾市</a></li><li><a href='javascript:;'>吕梁市</a></li><li><a href='javascript:;'>运城市</a></li>",
        "<li><a href='javascript:;'>呼和浩特市</a></li><li><a href='javascript:;'>包头市</a></li><li><a href='javascript:;'>乌海市</a></li><li><a href='javascript:;'>赤峰市</a></li><li><a href='javascript:;'>通辽市</a></li><li><a href='javascript:;'>呼伦贝尔市</a></li><li><a href='javascript:;'>鄂尔多斯市</a></li><li><a href='javascript:;'>乌兰察布市</a></li><li><a href='javascript:;'>巴彦淖尔市</a></li><li><a href='javascript:;'>兴安盟</a></li><li><a href='javascript:;'>锡林郭勒盟</a></li><li><a href='javascript:;'>阿拉善盟</a></li>",
        "<li><a href='javascript:;'>沈阳市</a></li><li><a href='javascript:;'>朝阳市</a></li><li><a href='javascript:;'>阜新市</a></li><li><a href='javascript:;'>铁岭市</a></li><li><a href='javascript:;'>抚顺市</a></li><li><a href='javascript:;'>本溪市</a></li><li><a href='javascript:;'>辽阳市</a></li><li><a href='javascript:;'>鞍山市</a></li><li><a href='javascript:;'>丹东市</a></li><li><a href='javascript:;'>大连市</a></li><li><a href='javascript:;'>营口市</a></li><li><a href='javascript:;'>盘锦市</a></li><li><a href='javascript:;'>锦州市</a></li><li><a href='javascript:;'>葫芦岛市</a></li>",
        "<li><a href='javascript:;'>长春市</a></li><li><a href='javascript:;'>白城市</a></li><li><a href='javascript:;'>松原市</a></li><li><a href='javascript:;'>吉林市</a></li><li><a href='javascript:;'>四平市</a></li><li><a href='javascript:;'>辽源市</a></li><li><a href='javascript:;'>通化市</a></li><li><a href='javascript:;'>白山市</a></li><li><a href='javascript:;'>延边州</a></li>",
        "<li><a href='javascript:;'>哈尔滨市</a></li><li><a href='javascript:;'>齐齐哈尔市</a></li><li><a href='javascript:;'>七台河市</a></li><li><a href='javascript:;'>黑河市</a></li><li><a href='javascript:;'>大庆市</a></li><li><a href='javascript:;'>鹤岗市</a></li><li><a href='javascript:;'>伊春市</a></li><li><a href='javascript:;'>佳木斯市</a></li><li><a href='javascript:;'>双鸭山市</a></li><li><a href='javascript:;'>鸡西市</a></li><li><a href='javascript:;'>牡丹江市</a></li><li><a href='javascript:;'>绥化市</a></li><li><a href='javascript:;'>大兴安岭地区</a></li>",
        "<li><a href='javascript:;'>南京市</a></li><li><a href='javascript:;'>徐州市</a></li><li><a href='javascript:;'>连云港市</a></li><li><a href='javascript:;'>宿迁市</a></li><li><a href='javascript:;'>淮安市</a></li><li><a href='javascript:;'>盐城市</a></li><li><a href='javascript:;'>扬州市</a></li><li><a href='javascript:;'>泰州市</a></li><li><a href='javascript:;'>南通市</a></li><li><a href='javascript:;'>镇江市</a></li><li><a href='javascript:;'>常州市</a></li><li><a href='javascript:;'>无锡市</a></li><li><a href='javascript:;'>苏州市</a></li>",
        "<li><a href='javascript:;'>杭州市</a></li><li><a href='javascript:;'>湖州市</a></li><li><a href='javascript:;'>嘉兴市</a></li><li><a href='javascript:;'>舟山市</a></li><li><a href='javascript:;'>宁波市</a></li><li><a href='javascript:;'>绍兴市</a></li><li><a href='javascript:;'>衢州市</a></li><li><a href='javascript:;'>金华市</a></li><li><a href='javascript:;'>台州市</a></li><li><a href='javascript:;'>温州市</a></li><li><a href='javascript:;'>丽水市</a></li>",
        "<li><a href='javascript:;'>合肥市</a></li><li><a href='javascript:;'>宿州市</a></li><li><a href='javascript:;'>淮北市</a></li><li><a href='javascript:;'>亳州市</a></li><li><a href='javascript:;'>阜阳市</a></li><li><a href='javascript:;'>蚌埠市</a></li><li><a href='javascript:;'>淮南市</a></li><li><a href='javascript:;'>滁州市</a></li><li><a href='javascript:;'>马鞍山市</a></li><li><a href='javascript:;'>芜湖市</a></li><li><a href='javascript:;'>铜陵市</a></li><li><a href='javascript:;'>安庆市</a></li><li><a href='javascript:;'>黄山市</a></li><li><a href='javascript:;'>六安市</a></li><li><a href='javascript:;'>巢湖市</a></li><li><a href='javascript:;'>池州市</a></li><li><a href='javascript:;'>宣城市</a></li>",
        "<li><a href='javascript:;'>福州市</a></li><li><a href='javascript:;'>南平市</a></li><li><a href='javascript:;'>莆田市</a></li><li><a href='javascript:;'>三明市</a></li><li><a href='javascript:;'>泉州市</a></li><li><a href='javascript:;'>厦门市</a></li><li><a href='javascript:;'>漳州市</a></li><li><a href='javascript:;'>龙岩市</a></li><li><a href='javascript:;'>宁德市</a></li>",
        "<li><a href='javascript:;'>南昌市</a></li><li><a href='javascript:;'>九江市</a></li><li><a href='javascript:;'>景德镇市</a></li><li><a href='javascript:;'>鹰潭市</a></li><li><a href='javascript:;'>新余市</a></li><li><a href='javascript:;'>萍乡市</a></li><li><a href='javascript:;'>赣州市</a></li><li><a href='javascript:;'>上饶市</a></li><li><a href='javascript:;'>抚州市</a></li><li><a href='javascript:;'>宜春市</a></li><li><a href='javascript:;'>吉安市</a></li>",
        "<li><a href='javascript:;'>济南市</a></li><li><a href='javascript:;'>青岛市</a></li><li><a href='javascript:;'>聊城市</a></li><li><a href='javascript:;'>德州市</a></li><li><a href='javascript:;'>东营市</a></li><li><a href='javascript:;'>淄博市</a></li><li><a href='javascript:;'>潍坊市</a></li><li><a href='javascript:;'>烟台市</a></li><li><a href='javascript:;'>威海市</a></li><li><a href='javascript:;'>日照市</a></li><li><a href='javascript:;'>临沂市</a></li><li><a href='javascript:;'>枣庄市</a></li><li><a href='javascript:;'>济宁市</a></li><li><a href='javascript:;'>泰安市</a></li><li><a href='javascript:;'>莱芜市</a></li><li><a href='javascript:;'>滨州市</a></li><li><a href='javascript:;'>菏泽市</a></li>",
        "<li><a href='javascript:;'>郑州市</a></li><li><a href='javascript:;'>开封市</a></li><li><a href='javascript:;'>三门峡市</a></li><li><a href='javascript:;'>洛阳市</a></li><li><a href='javascript:;'>焦作市</a></li><li><a href='javascript:;'>新乡市</a></li><li><a href='javascript:;'>鹤壁市</a></li><li><a href='javascript:;'>安阳市</a></li><li><a href='javascript:;'>濮阳市</a></li><li><a href='javascript:;'>商丘市</a></li><li><a href='javascript:;'>许昌市</a></li><li><a href='javascript:;'>漯河市</a></li><li><a href='javascript:;'>平顶山市</a></li><li><a href='javascript:;'>南阳市</a></li><li><a href='javascript:;'>信阳市</a></li><li><a href='javascript:;'>周口市</a></li><li><a href='javascript:;'>驻马店市</a></li><li><a href='javascript:;'>济源市</a></li>",
        "<li><a href='javascript:;'>武汉市</a></li><li><a href='javascript:;'>十堰市</a></li><li><a href='javascript:;'>襄樊市</a></li><li><a href='javascript:;'>荆门市</a></li><li><a href='javascript:;'>孝感市</a></li><li><a href='javascript:;'>黄冈市</a></li><li><a href='javascript:;'>鄂州市</a></li><li><a href='javascript:;'>黄石市</a></li><li><a href='javascript:;'>咸宁市</a></li><li><a href='javascript:;'>荆州市</a></li><li><a href='javascript:;'>宜昌市</a></li><li><a href='javascript:;'>随州市</a></li><li><a href='javascript:;'>省直辖县级行政单位</a></li><li><a href='javascript:;'>恩施州</a></li>",
        "<li><a href='javascript:;'>长沙市</a></li><li><a href='javascript:;'>张家界市</a></li><li><a href='javascript:;'>常德市</a></li><li><a href='javascript:;'>益阳市</a></li><li><a href='javascript:;'>岳阳市</a></li><li><a href='javascript:;'>株洲市</a></li><li><a href='javascript:;'>湘潭市</a></li><li><a href='javascript:;'>衡阳市</a></li><li><a href='javascript:;'>郴州市</a></li><li><a href='javascript:;'>永州市</a></li><li><a href='javascript:;'>邵阳市</a></li><li><a href='javascript:;'>怀化市</a></li><li><a href='javascript:;'>娄底市</a></li><li><a href='javascript:;'>湘西州</a></li>",
        "<li><a href='javascript:;'>广州市</a></li><li><a href='javascript:;'>深圳市</a></li><li><a href='javascript:;'>清远市</a></li><li><a href='javascript:;'>韶关市</a></li><li><a href='javascript:;'>河源市</a></li><li><a href='javascript:;'>梅州市</a></li><li><a href='javascript:;'>潮州市</a></li><li><a href='javascript:;'>汕头市</a></li><li><a href='javascript:;'>揭阳市</a></li><li><a href='javascript:;'>汕尾市</a></li><li><a href='javascript:;'>惠州市</a></li><li><a href='javascript:;'>东莞市</a></li><li><a href='javascript:;'>珠海市</a></li><li><a href='javascript:;'>中山市</a></li><li><a href='javascript:;'>江门市</a></li><li><a href='javascript:;'>佛山市</a></li><li><a href='javascript:;'>肇庆市</a></li><li><a href='javascript:;'>云浮市</a></li><li><a href='javascript:;'>阳江市</a></li><li><a href='javascript:;'>茂名市</a></li><li><a href='javascript:;'>湛江市</a></li>",
        "<li><a href='javascript:;'>南宁市</a></li><li><a href='javascript:;'>桂林市</a></li><li><a href='javascript:;'>柳州市</a></li><li><a href='javascript:;'>梧州市</a></li><li><a href='javascript:;'>贵港市</a></li><li><a href='javascript:;'>玉林市</a></li><li><a href='javascript:;'>钦州市</a></li><li><a href='javascript:;'>北海市</a></li><li><a href='javascript:;'>防城港市</a></li><li><a href='javascript:;'>崇左市</a></li><li><a href='javascript:;'>百色市</a></li><li><a href='javascript:;'>河池市</a></li><li><a href='javascript:;'>来宾市</a></li><li><a href='javascript:;'>贺州市<li><a href='javascript:;'>",
        "<li><a href='javascript:;'>海口市</a></li><li><a href='javascript:;'>三亚市</a></li><li><a href='javascript:;'>省直辖行政单位</a></li>",
        "<li><a href='javascript:;'>成都市</a></li><li><a href='javascript:;'>广元市</a></li><li><a href='javascript:;'>绵阳市</a></li><li><a href='javascript:;'>德阳市</a></li><li><a href='javascript:;'>南充市</a></li><li><a href='javascript:;'>广安市</a></li><li><a href='javascript:;'>遂宁市</a></li><li><a href='javascript:;'>内江市</a></li><li><a href='javascript:;'>乐山市</a></li><li><a href='javascript:;'>自贡市</a></li><li><a href='javascript:;'>泸州市</a></li><li><a href='javascript:;'>宜宾市</a></li><li><a href='javascript:;'>攀枝花市</a></li><li><a href='javascript:;'>巴中市</a></li><li><a href='javascript:;'>达州市</a></li><li><a href='javascript:;'>资阳市</a></li><li><a href='javascript:;'>眉山市</a></li><li><a href='javascript:;'>雅安市</a></li><li><a href='javascript:;'>阿坝州</a></li><li><a href='javascript:;'>甘孜州</a></li><li><a href='javascript:;'>凉山州</a></li>",
        "<li><a href='javascript:;'>贵阳市</a></li><li><a href='javascript:;'>六盘水市</a></li><li><a href='javascript:;'>遵义市</a></li><li><a href='javascript:;'>安顺市</a></li><li><a href='javascript:;'>毕节地区</a></li><li><a href='javascript:;'>铜仁地区</a></li><li><a href='javascript:;'>黔东南州</a></li><li><a href='javascript:;'>黔南州</a></li><li><a href='javascript:;'>黔西南州</a></li>",
        "<li><a href='javascript:;'>昆明市</a></li><li><a href='javascript:;'>曲靖市</a></li><li><a href='javascript:;'>玉溪市</a></li><li><a href='javascript:;'>保山市</a></li><li><a href='javascript:;'>昭通市</a></li><li><a href='javascript:;'>丽江市</a></li><li><a href='javascript:;'>思茅市</a></li><li><a href='javascript:;'>临沧市</a></li><li><a href='javascript:;'>德宏州</a></li><li><a href='javascript:;'>怒江州</a></li><li><a href='javascript:;'>迪庆州</a></li><li><a href='javascript:;'>大理州</a></li><li><a href='javascript:;'>楚雄州</a></li><li><a href='javascript:;'>红河州</a></li><li><a href='javascript:;'>文山州</a></li><li><a href='javascript:;'>西双版纳州</a></li>",
        "<li><a href='javascript:;'>拉萨市</a></li><li><a href='javascript:;'>那曲地区</a></li><li><a href='javascript:;'>昌都地区</a></li><li><a href='javascript:;'>林芝地区</a></li><li><a href='javascript:;'>山南地区</a></li><li><a href='javascript:;'>日喀则地区</a></li><li><a href='javascript:;'>阿里地区</a></li>",
        "<li><a href='javascript:;'>西安市</a></li><li><a href='javascript:;'>延安市</a></li><li><a href='javascript:;'>铜川市</a></li><li><a href='javascript:;'>渭南市</a></li><li><a href='javascript:;'>咸阳市</a></li><li><a href='javascript:;'>宝鸡市</a></li><li><a href='javascript:;'>汉中市</a></li><li><a href='javascript:;'>榆林市</a></li><li><a href='javascript:;'>安康市</a></li><li><a href='javascript:;'>商洛市</a></li>",
        "<li><a href='javascript:;'>兰州市</a></li><li><a href='javascript:;'>嘉峪关市</a></li><li><a href='javascript:;'>白银市</a></li><li><a href='javascript:;'>天水市</a></li><li><a href='javascript:;'>武威市</a></li><li><a href='javascript:;'>酒泉市</a></li><li><a href='javascript:;'>张掖市</a></li><li><a href='javascript:;'>庆阳市</a></li><li><a href='javascript:;'>平凉市</a></li><li><a href='javascript:;'>定西市</a></li><li><a href='javascript:;'>陇南市</a></li><li><a href='javascript:;'>临夏州</a></li><li><a href='javascript:;'>甘南州</a></li>",
        "<li><a href='javascript:;'>西宁市</a></li><li><a href='javascript:;'>海东地区</a></li><li><a href='javascript:;'>海北州</a></li><li><a href='javascript:;'>海南州</a></li><li><a href='javascript:;'>黄南州</a></li><li><a href='javascript:;'>果洛州</a></li><li><a href='javascript:;'>玉树州</a></li><li><a href='javascript:;'>海西州</a></li>",
        "<li><a href='javascript:;'>银川市</a></li><li><a href='javascript:;'>石嘴山市</a></li><li><a href='javascript:;'>吴忠市</a></li><li><a href='javascript:;'>固原市</a></li><li><a href='javascript:;'>中卫市</a></li>",
        "<li><a href='javascript:;'>乌鲁木齐市</a></li><li><a href='javascript:;'>克拉玛依市</a></li><li><a href='javascript:;'>自治区直辖县级行政单位</a></li><li><a href='javascript:;'>喀什地区</a></li><li><a href='javascript:;'>阿克苏地区</a></li><li><a href='javascript:;'>和田地区</a></li><li><a href='javascript:;'>吐鲁番地区</a></li><li><a href='javascript:;'>哈密地区</a></li><li><a href='javascript:;'>克孜勒苏柯州</a></li><li><a href='javascript:;'>博尔塔拉州</a></li><li><a href='javascript:;'>昌吉州</a></li><li><a href='javascript:;'>巴音郭楞州</a></li><li><a href='javascript:;'>伊犁州</a></li><li><a href='javascript:;'>塔城地区</a></li><li><a href='javascript:;'>阿勒泰地区</a></li>",
        "<li><a href='javascript:;'>香港特别行政区</a></li>",
        "<li><a href='javascript:;'>澳门特别行政区</a></li>",
        "<li><a href='javascript:;'>台北</a></li><li><a href='javascript:;'>高雄</a></li><li><a href='javascript:;'>台中</a></li><li><a href='javascript:;'>花莲</a></li><li><a href='javascript:;'>基隆</a></li><li><a href='javascript:;'>嘉义</a></li><li><a href='javascript:;'>金门</a></li><li><a href='javascript:;'>连江</a></li><li><a href='javascript:;'>苗栗</a></li><li><a href='javascript:;'>南投</a></li><li><a href='javascript:;'>澎湖</a></li><li><a href='javascript:;'>屏东</a></li><li><a href='javascript:;'>台东</a></li><li><a href='javascript:;'>台南</a></li><li><a href='javascript:;'>桃园</a></li><li><a href='javascript:;'>新竹</a></li><li><a href='javascript:;'>宜兰</a></li><li><a href='javascript:;'>云林</a></li><li><a href='javascript:;'>彰化</a></li>"
    );
    //=============================================定义省市结束========================================//


});

